# Generated by Django 5.0.4 on 2024-04-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/<django.db.models.query_utils.DeferredAttribute object at 0x79a23a7ffa70>-<property object at 0x79a23b91d030>'),
        ),
    ]
